### ISSUE TITLE
Notebook ch 17

### ISSUE THREAD

**Issue by venturam71** [CausalAIBook/MetricsMLNotebooks#9]
Please fix the notebboks of ch 17 on RDD.

**Comment by OliverSchacht** [comment]
Hi @venturam71, 
thanks for creating this issue. 
Could you please specify what exactly your issue(s) with running these notebooks is.
I was able to run them without any errors.
Thanks, 
Oliver

**Comment by OliverSchacht** [comment]
Hi @venturam71 I am closing this for now as the error cannot be reproduced, but if you want to come back reporting what goes wrong for you feel free to reopen.
Thanks!
